export const REGISTER_PATIENT_REQUEST = 'REGISTER_PATIENT_REQUEST';
export const REGISTER_PATIENT_SUCCESS = 'REGISTER_PATIENT_SUCCESS';

export const REGISTER_DOCTOR_REQUEST = 'REGISTER_PATIENT_REQUEST';
export const REGISTER_DOCTOR_SUCCESS = 'REGISTER_PATIENT_SUCCESS';