export const FIND_DOCTOR_REQUEST = 'GET_DOCTOR_REQUEST';
export const FIND_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';

export const APPROVE_DOCTOR_REQUEST = 'APPROVE_DOCTOR_REQUEST';
export const APPROVE_DOCTOR_SUCCESS = 'APPROVE_DOCTOR_SUCCESS';

export const GET_INCOMING_REQUESTS_REQUEST = 'GET_INCOMING_REQUESTS_REQUEST';
export const GET_INCOMING_REQUESTS_SUCCESS = 'GET_INCOMING_REQUESTS_SUCCESS';

export const CONSIDER_REQUEST = 'CONSIDER_REQUEST';
export const CONSIDER_SUCCESS = 'CONSIDER_SUCCESS';

export const GET_RECORDS_REQUEST = 'GET_RECORDS_REQUEST';
export const GET_RECORDS_SUCCESS = 'GET_RECORDS_SUCCESS';