export const FIND_DOCTOR_REQUEST = 'GET_DOCTOR_REQUEST';
export const FIND_DOCTOR_SUCCESS = 'GET_DOCTOR_SUCCESS';

export const APPROVE_DOCTOR_REQUEST = 'APPROVE_DOCTOR_REQUEST';
export const APPROVE_DOCTOR_SUCCESS = 'APPROVE_DOCTOR_SUCCESS';