export const FIND_PATIENT_REQUEST = 'FIND_PATIENT_REQUEST';
export const FIND_PATIENT_SUCCESS = 'FIND_PATIENT_SUCCESS';

export const REQUEST_PATIENT_PERMISSION_REQUEST = 'REQUEST_PATIENT_PERMISSION_REQUEST';
export const REQUEST_PATIENT_PERMISSION_SUCCESS = 'REQUEST_PATIENT_PERMISSION_SUCCESS';

export const ADD_RECORD_REQUEST = 'ADD_RECORD_REQUEST';
export const ADD_RECORD_SUCCESS = 'ADD_RECORD_SUCCESS';